<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: youssouf
 * Date: Mon, 30 Apr 2018 20:47:07 +0200
 */

$conf['title'] = 'Wiki ubuntu-fr <sup>&#57599;</sup>';
$conf['start'] = 'Accueil';
$conf['lang'] = 'fr';
$conf['template'] = 'bootstrap3';
$conf['tagline'] = 'La Documentation francophone';
$conf['license'] = 'cc-by-sa';
$conf['allowdebug'] = 1;
$conf['recent'] = 40;
$conf['recent_days'] = 400;
$conf['breadcrumbs'] = 0;
$conf['typography'] = '0';
$conf['dformat'] = 'Le %d/%m/%Y, %H:%M';
$conf['signature'] = '--- //[[:utilisateurs:@USER@|@USER@]] @DATE@//';
$conf['toptoclevel'] = '2';
$conf['useacl'] = 1;
$conf['disableactions'] = 'register,resendpwd,profile,check,debug';
$conf['indexdelay'] = 0;
$conf['locktime'] = 10*60;
$conf['fetchsize'] = 2*1024*1024;
$conf['subscribers'] = 1;
$conf['notify'] = 'ubuntu_wiki_modifs-fr@lists.ubuntu-eu.org';
$conf['mailfrom'] = 'ufr_doc@ubuntu-fr.org';
$conf['mailprefix'] = 'UFrDoc';
$conf['htmlmail'] = 0;
$conf['rss_update'] = 20*60;
$conf['userewrite'] = '2';
$conf['useslash'] = 1;
$conf['compress'] = 0;
$conf['compression'] = '0';
$conf['readdircache'] = 120;
$conf['plugin']['authmysql']['TablesToLock'] = array();
$conf['plugin']['tag']['namespace'] = ':';
$conf['plugin']['tag']['pagelist_flags'] = 'table,header,nodate,nouser';
$conf['tpl']['bootstrap3']['bootstrapTheme'] = 'bootswatch';
$conf['tpl']['bootstrap3']['bootswatchTheme'] = 'united';
$conf['tpl']['bootstrap3']['showThemeSwitcher'] = 1;
$conf['tpl']['bootstrap3']['fixedTopNavbar'] = 1;
$conf['tpl']['bootstrap3']['fluidContainer'] = 1;
$conf['tpl']['bootstrap3']['pageToolsAnimation'] = 0;
$conf['tpl']['bootstrap3']['showPageId'] = 0;
$conf['tpl']['bootstrap3']['tocCollapsed'] = 1;
$conf['tpl']['bootstrap3']['showCookieLawBanner'] = 1;
$conf['tpl']['bootstrap3']['browserTitle'] = 'LOCAL-@TITLE@ ';
$conf['is_dev'] = '0';
$conf['spellchecker'] = '0';

// end auto-generated content
