<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: youssouf
 * Date: Tue, 24 Apr 2018 23:15:21 +0200
 */

$conf['title'] = 'ubuntu-fr-doc';
$conf['start'] = 'Accueil';
$conf['lang'] = 'fr';
$conf['template'] = 'bootstrap3';
$conf['license'] = 'cc-by-sa';
$conf['youarehere'] = 1;
$conf['sneaky_index'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['tpl']['bootstrap3']['bootstrapTheme'] = 'bootswatch';
$conf['tpl']['bootstrap3']['bootswatchTheme'] = 'united';
$conf['tpl']['bootstrap3']['customTheme'] = './';
$conf['tpl']['bootstrap3']['showThemeSwitcher'] = 1;
$conf['tpl']['bootstrap3']['sidebarOnNavbar'] = 1;
$conf['tpl']['bootstrap3']['fixedTopNavbar'] = 1;
$conf['tpl']['bootstrap3']['individualTools'] = 1;
$conf['tpl']['bootstrap3']['showIndividualTool'] = '';
$conf['tpl']['bootstrap3']['fluidContainer'] = 1;
$conf['tpl']['bootstrap3']['pageOnPanel'] = 0;
$conf['tpl']['bootstrap3']['showBadges'] = 0;
$conf['tpl']['bootstrap3']['showWikiInfo'] = 0;
$conf['tpl']['bootstrap3']['tocCollapsed'] = 1;

// end auto-generated content
